appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
provider:
  win: azure
travis:
  secure:
    BINSTAR_TOKEN: Xnh83+XY8CFIq9IK0oAfJDYlD8TFv3+JRr4tz2wt5fsPkjlLgY24WXSZ1LzOF554TrKG+kltVo/VrVr6aOt2KmhLbH3b4VOoGbhSznEarwVGPU77KnJ/MogZ/PepnJqikrxn4IPGdkMXGPo47uBLz/9PLfB6fHKx8WPsGmhd5D2ZvkfcJto4aQEBGBJlRTYzk2aqeeMlym8qYjYyTboCnHrM5DqRUspaikOcDgp/dB7N+9mg0DAdbVfS41NLh8baPThtahki78SIyyRiznYIRFylZKpCev8VNUpR4XqzKqOrIaVZyirTb3lwnKKCJzSDABrZqjQ5zc1unQ8sz5p9N+9lfgHqFOPdIU9LG3/fE1TErRPKRUzqIQIj2ArS0zMhWdFVB14LsgE1Igjv1w/FaYCcgwqx22ywleDCiBhNqYgmi4qwnvSoaR9es1ubh4N1gEK5Mr12kYO+3gc467ZYNhqXcTtsCCVAiWmguZNR6gFciHVX+m/UDhx9TOvALWXuFUUkavCm/n0eFFdXVdx7gGUhxrovtgxsq3YcRLIFPY4B5lA30wpVL4sehg7x7NjFmneEmFnI3a9EvPe4cyZezRjWO39uGuJ38SxNnn36h4b0C2zTYOzazNgGt9WYLzdpqMr0RQ/7PgSIzHaYPT1OxO1Z62gmETcgGgsxFQ0qfiE=
conda_forge_output_validation: true
