travis:
  secure:
    BINSTAR_TOKEN: 3v9Grz5MMCZsmanRGPTlGb9O0oxq8od4HZDb/XTrtmyJuao+icW3DLKnW7VM5pqEvLiZ7w5Rnu57H7CGmfuhqWmHWpNhLedIgXYp7Z0SaMZmzFP+hfr49+C7SXIBVnxbEwsi/e1VDQ4SxrKnGdtNr7KS7ccfRZu3hqXb8njhCXnGP2MNoF50qPiLj5pp4GeiYDLnI8H9HL6qNWi9LxVJhDZyawGd5/YCSh5MyMgZ+FOBaWGrdXMS/ac7PiG0ujeqo3rsYnfnESuCbQpWO4Az03PFBRd2JUfxGQRBXCJuRmAEmrFcTGM/cVG3W6RPRH1YSJhE0WxuAONqTQ4EZzH8HuRJFEuJFgwqenqJdrfWA+oVfjreWwnLOyai5KtqnnIXAv0tBbW1O2A+VSn11kEZcP5/1y896IZzWZ80IQKt/UojeZi7mQpQ4ymfSwzkHbVkVKm7IZDFZFL74PyfrO6GGaaHJSdYBNQfvsHqoeUibLwKO5sQdPwmYxu0hhuzAS1dB8xRaq0S1bMF+nobXRKBuA1355+s8y4oWUJMorSpYFGPyWAj92unLPa1IzTncoDLrM8FvZtqowXSZmUkU1Yx3SFqsiGytQn9cigrabzl4xXuesp5XG73Omppa2I9Bc9HL5e0wYrstm+DqCwpzCEbRPdBUGxx1+RVTwrZ0HF4OUs=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
